### ISSUE TITLE
Error on serverless deploy

### ISSUE THREAD

**Issue by ritwik-dell** [tscanlin/serverless-s3-crud#1]
Hi,
I am pretty new to serverless framework. I tried downloading your code and running it using serverless deploy. However, I get the following error every time:
```
ServerlessError: An error occurred while provisioning your stack: MyBucket - form-response
 already exists.
```

Here is the complete stack of logs while running deploy in verbose mode.
Note: I am running it in almost a brand new AWS account where there are no S3 buckets defined at all.

Please help.

```
C:\All\Practice\Microservices\svrlessfwk\serverless-s3-crud>serverless deploy -v
Serverless: Packaging service...
Serverless: Creating Stack...
Serverless: Checking Stack create progress...
CloudFormation - CREATE_IN_PROGRESS - AWS::CloudFormation::Stack - serverless-crud-s3-dev
CloudFormation - CREATE_IN_PROGRESS - AWS::S3::Bucket - ServerlessDeploymentBucket
CloudFormation - CREATE_IN_PROGRESS - AWS::S3::Bucket - ServerlessDeploymentBucket
CloudFormation - CREATE_COMPLETE - AWS::S3::Bucket - ServerlessDeploymentBucket
CloudFormation - CREATE_COMPLETE - AWS::CloudFormation::Stack - serverless-crud-s3-dev
Serverless: Stack create finished...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service .zip file to S3 (4.59 MB)...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
CloudFormation - UPDATE_IN_PROGRESS - AWS::CloudFormation::Stack - serverless-crud-s3-dev
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - ListLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::S3::Bucket - MyBucket
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - UpdateLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - ListLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - ReadOneLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - CreateLogGroup
CloudFormation - CREATE_COMPLETE - AWS::Logs::LogGroup - ListLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - ReadOneLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - DeleteLogGroup
CloudFormation - CREATE_COMPLETE - AWS::Logs::LogGroup - ReadOneLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - CreateLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - UpdateLogGroup
CloudFormation - CREATE_COMPLETE - AWS::Logs::LogGroup - CreateLogGroup
CloudFormation - CREATE_COMPLETE - AWS::Logs::LogGroup - UpdateLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - CREATE_IN_PROGRESS - AWS::ApiGateway::RestApi - ApiGatewayRestApi
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - ReadAllLogGroup
CloudFormation - CREATE_IN_PROGRESS - AWS::Logs::LogGroup - DeleteLogGroup
CloudFormation - CREATE_FAILED - AWS::S3::Bucket - MyBucket
CloudFormation - CREATE_COMPLETE - AWS::Logs::LogGroup - DeleteLogGroup
CloudFormation - CREATE_FAILED - AWS::Logs::LogGroup - ReadAllLogGroup
CloudFormation - CREATE_FAILED - AWS::ApiGateway::RestApi - ApiGatewayRestApi
CloudFormation - CREATE_FAILED - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - UPDATE_ROLLBACK_IN_PROGRESS - AWS::CloudFormation::Stack - serverless-cru
d-s3-dev
CloudFormation - UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS - AWS::CloudFormation::Stack
 - serverless-crud-s3-dev
CloudFormation - DELETE_IN_PROGRESS - AWS::Logs::LogGroup - CreateLogGroup
CloudFormation - DELETE_IN_PROGRESS - AWS::Logs::LogGroup - UpdateLogGroup
CloudFormation - DELETE_IN_PROGRESS - AWS::ApiGateway::RestApi - ApiGatewayRestApi
CloudFormation - DELETE_IN_PROGRESS - AWS::Logs::LogGroup - ReadOneLogGroup
CloudFormation - DELETE_IN_PROGRESS - AWS::Logs::LogGroup - ListLogGroup
CloudFormation - DELETE_IN_PROGRESS - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - DELETE_IN_PROGRESS - AWS::Logs::LogGroup - ReadAllLogGroup
CloudFormation - DELETE_COMPLETE - AWS::S3::Bucket - MyBucket
CloudFormation - DELETE_IN_PROGRESS - AWS::Logs::LogGroup - DeleteLogGroup
CloudFormation - DELETE_COMPLETE - AWS::Logs::LogGroup - CreateLogGroup
CloudFormation - DELETE_COMPLETE - AWS::Logs::LogGroup - UpdateLogGroup
CloudFormation - DELETE_COMPLETE - AWS::ApiGateway::RestApi - ApiGatewayRestApi
CloudFormation - DELETE_COMPLETE - AWS::Logs::LogGroup - ReadOneLogGroup
CloudFormation - DELETE_COMPLETE - AWS::Logs::LogGroup - ListLogGroup
CloudFormation - DELETE_COMPLETE - AWS::Logs::LogGroup - ReadAllLogGroup
CloudFormation - DELETE_COMPLETE - AWS::Logs::LogGroup - DeleteLogGroup
CloudFormation - DELETE_COMPLETE - AWS::IAM::Role - IamRoleLambdaExecution
CloudFormation - UPDATE_ROLLBACK_COMPLETE - AWS::CloudFormation::Stack - serverless-crud-s
3-dev
Serverless: Deployment failed!

  Serverless Error ---------------------------------------

  An error occurred while provisioning your stack: MyBucket - form-response already exists
.

  Stack Trace --------------------------------------------

ServerlessError: An error occurred while provisioning your stack: MyBucket - form-response
 already exists.
    at C:\Users\My\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\lib\monitorStack.js:113:33
From previous event:
    at AwsDeploy.monitorStack (C:\Users\My\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\lib\monitorStack.js:26:12)
    at C:\Users\My\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\lib\updateStack.js:88:30
From previous event:
    at AwsDeploy.update (C:\Users\My\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\lib\updateStack.js:88:8)
From previous event:
    at AwsDeploy.<anonymous> (C:\Users\My\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\lib\updateStack.js:105:12)
From previous event:
    at AwsDeploy.updateStack (C:\Users\My\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\lib\updateStack.js:99:8)
From previous event:
    at AwsDeploy.<anonymous> (C:\Users\My\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\deploy\index.js:125:39)
From previous event:
    at Object.AwsDeploy.hooks.aws:deploy:deploy:updateStack [as hook] (C:\Users\My\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\deploy\index.js:121:10)
    at C:\Users\My\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:218:55
From previous event:
    at PluginManager.invoke (C:\Users\My\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:218:22)
    at PluginManager.spawn (C:\Users\My\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:230:17)
    at AwsDeploy.<anonymous> (C:\Users\My\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\deploy\index.js:91:48)
From previous event:
    at Object.AwsDeploy.hooks.deploy:deploy [as hook] (C:\Users\My\AppData\Roaming\npm\node_modules\serverless\lib\plugins\aws\deploy\index.js:87:10)
    at C:\Users\My\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:218:55
From previous event:
    at PluginManager.invoke (C:\Users\My\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:218:22)
    at PluginManager.run (C:\Users\My\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:237:17)
    at C:\Users\My\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:99:33
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at Serverless.run (C:\Users\My\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:86:74)
    at C:\Users\My\AppData\Roaming\npm\node_modules\serverless\bin\serverless:39:50

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless

  Your Environment Information -----------------------------
     OS:                     win32
     Node Version:           4.2.4
     Serverless Version:     1.18.0

```

**Comment by tscanlin** [comment]
In aws bucket names need to be globally unique, so after installing but before deploying you need to change references to the bucket from "form-response" to your own bucket name.

**Comment by ritwik-dell** [comment]
@tscanlin thanks for the tip. I am now able to successfully deploy the entire service. However, when I am trying to call any of its end points, I am getting the following error (from CloudWatch logs)

```
Unable to import module 'handler': Error
at Function.Module._resolveFilename (module.js:325:15)
at Function.Module._load (module.js:276:25)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at Object.<anonymous> (/var/task/node_modules/aws-sdk/lib/xml/builder.js:2:15)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Module.require (module.js:353:17)
```

Any idea what this is? Note: I have not modified anything in the code other than the bucket name.

Regards,
Ritwik

**Comment by tscanlin** [comment]
There's probably something else that needs renaming or configuration in aws. But its hard to know for sure without being able to look at it.
